language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - redis-server
env:
  - TEST_HIREDIS=0
  - TEST_HIREDIS=1
before_install:
  - pip install --upgrade pytest
install:
  - pip install -e .
  - pip install -r dev_requirements.txt
  - "if [[ $TEST_HIREDIS == '1' ]]; then pip install hiredis; fi"
script: "pytest tests/client/"
matrix:
  include:
    - python: "3.5"
